Class OPCUA.Types.ArrayDataValue.TimeStamp Extends OPCUA.Types.AbstractDataValue
{

Property Values As list Of %TimeStamp;

Storage Default
{
<Data name="AbstractDataValueState">
<Value name="1">
<Value>SourceTimeStamp</Value>
</Value>
<Value name="2">
<Value>ServerTimeStamp</Value>
</Value>
<Value name="3">
<Value>Status</Value>
</Value>
<Value name="4">
<Value>Values</Value>
</Value>
</Data>
<Type>%Storage.Serial</Type>
}

}
