#!/bin/bash

echo
echo "### HOOK - build environment:"
echo "   SOURCE_BRANCH  : $SOURCE_BRANCH"
echo "   SOURCE_COMMIT  : $SOURCE_COMMIT"
echo "   COMMIT_MSG     : $COMMIT_MSG"
echo "   DOCKER_REPO    : $DOCKER_REPO"
echo "   DOCKERFILE_PATH: $DOCKERFILE_PATH"
echo "   DOCKER_TAG     : $DOCKER_TAG"
echo "   DOCKER_TAG     : $IMAGE_NAME"

./generate_certificates.sh

# Building the IRIS Image
docker build -t ${DOCKER_REPO}:iris-${DOCKER_TAG} ./image-iris

# Building the OPCUA Certified Server Image
docker build -t ${DOCKER_REPO}:server-ctt-${DOCKER_TAG} ./image-opcua-certified-server